# Generated by Django 5.1.7 on 2025-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('г', 'грамм'), ('мл', 'миллилитр'), ('шт', 'штука'), ('ч.л.', 'ч.л.'), ('ст.л.', 'ст.л.')], default='г', max_length=10, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(verbose_name='Количество'),
        ),
    ]
